//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleCalculator.Properties.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the first number: .
        /// </summary>
        internal static string FirstNumberRequest {
            get {
                return ResourceManager.GetString("FirstNumberRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first input needs to be a number (e.g 6, 7, 8, ...).
        /// </summary>
        internal static string FirstNumberTypeError {
            get {
                return ResourceManager.GetString("FirstNumberTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the operator (+, -, *, /, add, subtract, multiply, divide):.
        /// </summary>
        internal static string OperatorRequest {
            get {
                return ResourceManager.GetString("OperatorRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator is not valid. It must be one of the following (+, -, *, /, add, subtract, multiply, divide)..
        /// </summary>
        internal static string OperatorRequestError {
            get {
                return ResourceManager.GetString("OperatorRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of .
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the second number: .
        /// </summary>
        internal static string SecondNumberRequest {
            get {
                return ResourceManager.GetString("SecondNumberRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second input needs to be a number (eg, 6, 7 , 8, etc...).
        /// </summary>
        internal static string SecondNumberTypeError {
            get {
                return ResourceManager.GetString("SecondNumberTypeError", resourceCulture);
            }
        }
    }
}
